all: build

.PHONY: config
config:
	cmake -S . -B build \
		-DCCCORELIB_USE_TBB=ON \
		-DOPTION_USE_DXF_LIB=ON \
		-DOPTION_USE_GDAL=ON \
		-DOPTION_USE_SHAPE_LIB=ON \
		-DPLUGIN_GL_QEDL=ON \
		-DPLUGIN_GL_QSSAO=ON \
		-DPLUGIN_IO_QADDITIONAL=ON \
		-DPLUGIN_IO_QCORE=ON \
		-DPLUGIN_IO_QCSV_MATRIX=ON \
		-DPLUGIN_IO_QE57=ON \
		-DPLUGIN_IO_QFBX=OFF \
		-DPLUGIN_IO_QPDAL=ON \
		-DPLUGIN_IO_QPHOTOSCAN=ON \
		-DPLUGIN_IO_QRDB=OFF \
		-DCCCORELIB_USE_CGAL=ON \
		-DPLUGIN_STANDARD_QPCL=ON \
		-DPLUGIN_STANDARD_QANIMATION=ON \
		-DPLUGIN_STANDARD_QBROOM=ON \
		-DPLUGIN_STANDARD_QCANUPO=ON \
		-DPLUGIN_STANDARD_QCOMPASS=ON \
		-DPLUGIN_STANDARD_QCSF=ON \
		-DPLUGIN_STANDARD_QFACETS=ON \
		-DPLUGIN_STANDARD_QHOUGH_NORMALS=OFF \ # NOTE: plugin deactivated because it does not compile
		-DEIGEN_ROOT_DIR=$(nix eval -f '<nixpkgs>' --raw eigen)/include/eigen3 \
		-DPLUGIN_STANDARD_QHPR=ON \
		-DPLUGIN_STANDARD_QM3C2=ON \
		-DPLUGIN_STANDARD_QMPLANE=ON \
		-DPLUGIN_STANDARD_QPOISSON_RECON=ON \
		-DPLUGIN_STANDARD_QRANSAC_SD=ON \
		-DPLUGIN_STANDARD_QSRA=ON \
		-DPLUGIN_STANDARD_QCLOUDLAYERS=ON \
		-DPLUGIN_PYTHON=ON \
		-DCMAKE_BUILD_TYPE=Release

.PHONY: build
build: config plugins/private/CloudCompare-PythonPlugin
	cmake --build build

plugins/private/CloudCompare-PythonPlugin:
	git clone https://github.com/tmontaigu/CloudCompare-PythonPlugin plugins/private/CloudCompare-PythonPlugin
